### ISSUE TITLE
RangeError: Maximum call stack size exceeded when running my project

### ISSUE THREAD

**Issue by MichaelSu1983** [krakenjs/swaggerize-express#130]
I have a large swagger file about 100 endpoints, and create swaggerize express project. when I run node server.js, I got this error. Even I removed the enpoints in swagger file, but it does not help. 

what is the reason for this?

`node_modules/hoek/lib/index.js:24
    seen = { orig: [], copy: [] };
    ^

RangeError: Maximum call stack size exceeded
    at Object.exports.clone (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/hoek/lib/index.js:24:5)
    at internals.String.internals.Any.clone (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/joi/lib/any.js:114:24)
    at internals.String.internals.Any.allow (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/joi/lib/any.js:269:20)
    at regularString (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:229:39)
    at string (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:213:29)
    at resolvetype (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:95:29)
    at resolve (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:23:20)
    at /Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:144:25
    at Array.forEach (native)
    at resolveproperties (/Users/msu/swagger-mock/confluence-swagger-mock/node_modules/enjoi/lib/enjoi.js:139:41)`

**Comment by mbarsil** [comment]
Hi @MichaelSu1983 , did you manage to solve this?

**Comment by MichaelSu1983** [comment]
No, I just abandon the attempt for doing it. Is there any update on it?

**Comment by jsdevel** [comment]
@MichaelSu1983 one way to solve this is to use https://github.com/kogosoftwarellc/open-api
