### ISSUE TITLE
broken with getting started directions

### ISSUE THREAD

**Issue by coleGillespie** [krakenjs/swaggerize-express#98]
I am unable to install based on your directions

```
$ yo swaggerize
Swaggerize Generator
? What would you like to call this project: petstore
? Your name:
? Your github user name:
? Your email:
? Path (or URL) to swagger document: https://raw.githubusercontent.com/wordnik/swagger-spec/mast
er/examples/v2.0/json/petstore.json
? Express, Hapi or Restify: express
   create .jshintrc
   create .gitignore
   create .npmignore
   create server.js
   create package.json
   create README.md
   create config/petstore.json
   create handlers/pets.js
   create handlers/pets/{petId}.js
undefined:11
_.forEach(Object.keys(properties), function (prop) {;
                      ^

ReferenceError: properties is not defined
    at eval (eval at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:11:23)
    at underscore [as _engine] (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at engine (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at /usr/local/lib/node_modules/generator-swaggerize/app/index.js:287:18
    at Array.forEach (native)
    at yeoman.generators.Base.extend.models (/usr/local/lib/node_modules/generator-swaggerize/app/index.js:276:49)
    at /usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
```

**Comment by tlivings** [comment]
Assuming this is resolved.
